---
- hosts: all
  become: yes
  tasks:
    #- name: Set authorized key taken from file
    #  ansible.posix.authorized_key:
    #    user: priviauser
    #    state: present
    #    key: "{{ lookup('file', 'templates/priviauser.pub') }}"
    - name: Install Nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes
  
    - name: Copy files to server's document root
      copy:
        src: templates/server.html
        dest: "{{ document_root }}"
        mode: preserve
  
    - name: Apply Nginx template
      template:
        src: site.conf.j2
        dest: /etc/nginx/sites-available/default
      notify: Restart Nginx

  
    - name: Enable new site
      file:
        src: /etc/nginx/sites-available/default
        dest: /etc/nginx/sites-enabled/default
        state: link
      notify: Restart Nginx
    
  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted


